haskey(ENV,"ZEN_CORE") && pushfirst!(LOAD_PATH, ENV["ZEN_CORE"])

using Documenter
using ZenCore

makedocs(
    sitename = "Zen",
    clean = false,
    authors = "Li Huang <huangli@caep.cn> and contributors",
    format = Documenter.HTML(
        prettyurls = false,
        ansicolor = true,
        repolink = "https://github.com/huangli712/Zen",
        size_threshold = 409600, # 400kb
        assets = ["assets/zen.css"],
        collapselevel = 1,
    ),
    remotes = nothing,
    modules = [ZenCore],
    pages = [
        "Home" => "index.md",
        "Introduction" => Any[
            "Outline" => "intro/outline.md",
            "Strongly Correlated Materials" => "intro/sces.md",
            "Theoretical Methods" => Any[
                "Summary" => "intro/methods.md",
                "Density Functional Theory" => "intro/dft.md",
                "Dynamical Mean-Field Theory" => "intro/dmft.md",
                "The DFT + DMFT Method" => "intro/dft_dmft.md",
                "The DFT + DMFT Codes" => "intro/codes.md",
            ],
            "About The Zen Framework" => Any[
                "Summary" => "intro/about.md",
                "Motivation" => "intro/motivation.md",
                "Design Philosophy" => "intro/design.md",
                "Features" => "intro/features.md",
                "Future Plans" => "intro/future.md",
                "Citation" => "intro/cite.md",
                "Funding" => "intro/fund.md",
                "Developers" => "intro/team.md",
                "Technical Support" => "intro/support.md",
            ],
        ],
        "Getting Started" => Any[
            "Outline" => "start/outline.md",
            "Components" => "start/components.md",
            "Get The Code" => "start/obtain.md",
            "Uncompress" => "start/uncompress.md",
            "Directory Structure" => "start/directory.md",
            "Compile" => "start/compile.md",
            "Install" => "start/install.md",
            "Configure" => "start/configure.md",
            "The First Run" => "start/run.md",
            "Upgrade" => "start/upgrade.md",
        ],
        "Tutorials" => Any[
            "Outline" => "tutor/outline.md",
            "SrVO``_{3}``: Strongly Correlated Metal" => "tutor/SrVO3.md",
            "FeSe: Unconventional Superconuctor" => "tutor/FeSe.md",
            "MnO: Mott Insulator" => "tutor/MnO.md",
            "Ce: ``f``-Electron Metal" => "tutor/Ce.md",
        ],
        "Guide" => Any[
            "Outline" => "guide/outline.md",
            "Running Modes" => Any[
                "Summary" => "guide/modes.md",
                "Standard Mode" => "guide/standard.md",
                "REPL Mode" => "guide/repl.md",
                "Script Mode" => "guide/script.md",
            ],
            "Detailed Recipes" => Any[
                "Summary" => "guide/recipes.md",
                "Create Crystal Structure" => "guide/crystal.md",
                "Preprocess" => "guide/preprocess.md",
                "Preliminary Calculation" => "guide/preliminary.md",
                "Refine Configuration" => "guide/refine.md",
                "Start Calculation" => "guide/start.md",
                "Monitor Calculation" => "guide/monitor.md",
                "Postprocess" => "guide/postprocess.md",
                "Visualization" => "guide/plot.md",
                "One-Shot Calculation" => "guide/oneshot.md",
                "Charge Self-Consistent Calculation" => "guide/scf.md",
                "One-Component Calculation" => "guide/onecomp.md",
            ],
            "Input Files" => Any[
                "Summary" => "guide/input.md",
                "case.toml" => "guide/fcase.md",
                "MPI.toml" => "guide/fmpi.md",
                "POSCAR" => "guide/poscar.md",
                "QE.inp" => "guide/qeinp.md",
                "Pseudopotentials" => "guide/paw.md",
            ],
            "Output Files" => Any[
                "Summary" => "guide/output.md",
                "Standard Output" => "guide/fterm.md",
                "case.cycle" => "guide/fcycle.md",
                "case.log" => "guide/flog.md",
                "case.stop" => "guide/fstop.md",
                "case.test" => "guide/ftest.md",    
            ],
            "Input Parameters" => Any[
                "Summary" => "guide/parameters.md",
                "Block [case]" => "guide/block_case.md",
                "Block [dft]" => "guide/block_dft.md",
                "Block [dmft]" => "guide/block_dmft.md",
                "Block [imp]" => "guide/block_impurity.md",
                "Block [solver]" => "guide/block_solver.md",
            ],
            "Core Components" => Any[
                "Summary" => "guide/core.md",
                "Density Functional Theory Code" => "guide/dft.md",
                "Wannier Function Code" => "guide/wannier.md",
                "Dynamical Mean-Field Theory Code" => "guide/dmft.md",
                "Dual Fermion Code" => "guide/df.md",
                "Quantum Impurity Solvers" => "guide/qim.md",
            ],
            "Auxliary Components" => Any[
                "Summary" => "guide/auxiliary.md",
                "Graphic User Interface" => "guide/gui.md",
                "Auxiliary Tools" => "guide/tools.md",
                "Tests And Examples" => "guide/tests.md",
                "Documentation" => "guide/docs.md",
                "Projector Augmented Wave Datasets" => "guide/apawlib.md",
            ],
            "Tips And Tricks" => "guide/tips.md",
        ],
        "Internals" => Any[
            "Outline" => "internals/outline.md",
            "Software Architecture" => "internals/arch.md",
            "Inside The ZenCore Library" => Any[
                "Summary" => "internals/summary.md",
                "ZenCore" => "internals/zencore.md",
                "Global" => "internals/global.md",
                "Util" => "internals/util.md",
                "Tetra" => "internals/tetra.md",
                "Types" => "internals/types.md",
                "Config" => "internals/config.md",
                "Base" => "internals/base.md",
                "VASP" => "internals/vasp.md",
                "QE" => "internals/qe.md",
                "PLO" => "internals/plo.md",
                "Wannier" => "internals/wannier.md",
                "IR" => "internals/ir.md",
                "DMFT" => "internals/dmft.md",
                "Solver" => "internals/solver.md",
                "Sigma" => "internals/sigma.md",
                "Mixing" => "internals/mixing.md",
            ],
        ],
    ],
)
